### PR TITLE
Bump libxmljs dependency version

### PR DESCRIPTION
**Pull request by anotherpit**
To avoid compilation issues: https://github.com/polotek/libxmljs/issues/286

### CODE REVIEW

**Comment by anotherpit** [comment]
Would you mind publishing 0.1.4 tag

**Comment by trevordixon** [comment]
Already did.

**Comment by trevordixon** [comment]
That is, I published to npm. Are you asking that I tag it in git?

**Comment by anotherpit** [comment]
Nevermind, publishing to `npm` is enough for me, thanks.

**Pull request merged**
