### PR TITLE
updated libxmljs

### PR DESCRIPTION
**Pull request by clickclickonsal**
updated libxmljs to 0.18.0 to support Node v 6.x.x

### CODE REVIEW

**Comment by clickclickonsal** [comment]
I published a forked npm module with this fix, since it seems this library isn't actively maintained. https://www.npmjs.com/package/excel-fork

**Comment by trevordixon** [comment]
I'd rather make you a maintainer than have a confusing fork out there. Do you want to administer this one?

**Comment by clickclickonsal** [comment]
Sure. 👍🏻

**Comment by trevordixon** [comment]
Done. You can publish to npm too.

**Comment by clickclickonsal** [comment]
Awesome! Thank you!

**Pull request merged**
